### ISSUE TITLE
Logo for Transforming Organisational Software Sustainability Project

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/toss#12]
- [ ] Logo for Transforming Organisational Software Sustainability

**Comment by Jenya-design** [comment]
@seanmcilroy29 is TOSS Coummunity WG project?

**Comment by seanmcilroy29** [comment]
@Jenya-design - This is a Standards WG project

**Comment by Jenya-design** [comment]
@seanmcilroy29 please check 2 options for TOSS logo. v02 is more reminiscent of [Maturity Matrix logo](https://drive.google.com/file/d/18i6YxxNA1qJBE67fb6ugzSzF8Xc_U439/view?usp=sharing) in case it's important to show the link between these projects. Let me know what you think 

![Image](https://github.com/Green-Software-Foundation/toss/assets/69306070/6e7c02cc-12b2-4811-a84a-8319b62aefab)

**Comment by seanmcilroy29** [comment]
@Jenya-design - Option 2 looks great. As you've noted, this'll be aligned with the Maturity Matrix logo.

**Comment by Jenya-design** [comment]
Thank you @seanmcilroy29 
Files for v.02 of the logo here
https://drive.google.com/drive/folders/1x2v2sdo6nbPbdTaCZ_3HigO2aAxYnzgx?usp=sharing

**Comment by PindyBhullar** [comment]
Thank you @Jenya-design for the designs. They look great, and happy also to go with option 2.

**Comment by seanmcilroy29** [comment]
Completed
