### ISSUE TITLE
[Article] Transforming Organisational Software Sustainability

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/toss#13]
### Transforming Organisational Software Sustainability

**Proposer**: @seanmcilroy29 | Affiliation | GitHub Username)
**Abstract**: The initiative will concentrate on the broader organisation's adoption of calculations and the measures organisations must take to ensure that measuring CO2 is an integral part of application development for new and existing applications. Utilising sustainability frameworks such as TCFD, CSRD, and others to guide organisational priorities in incorporating CO2 data into strategic and executive decision-making.
**Why**: The framework and methodology will utilise the tools, standards, patterns, and principles developed by the Green Software Foundation as well as those that are available from external sources.  
**Audience**: This solution's intended audience comprises technology architects, devops lead engineers, programmers and project managers, product managers, business managers, and business executives. 
**Timeline**: Before

[Collaboration Doc](https://docs.google.com/document/d/15BhJo2LPzA49eqQGzXCpksm6ftsUWUBevmXwwyKyzOI/edit) outlining the Project details

## Important Information
_To be filled out later_

**Author**: (Who is assigned to write this article)
**Other contributors**: Project lead - Pindy Bhullar - pindy.bhullar@ubs.com 
**Article Link**: (Link to the doc, must be in our official GSF drive)
**Graphics Link**: In progress
**Published Link**: (The link the article was published to for memory)

## Checklist
- [ ] Idea discussed and selected for writing. _After checking this box, set Status to "Todo" under "Articles" project_
- [ ] Author identified. _After checking this box Assign issue to the Author_
- [ ] Scheduled in calendar
- [ ] Google doc link created in GSF drive. 
- [ ] In progress. _After checking this box, set Status to "In Progress" under "Articles" project_
- [ ] Draft created. _After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth_
- [ ] Draft reviewed. _After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects_
- [ ] Graphics created. _After checking this box, assign to TBC for approval._
- [ ] Approved. _After checking this box, assign to TBC for publishing._
- [ ] Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [ ] Shared on socials
- [ ] Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by ursvill** [comment]
@seanmcilroy29 - Is there appetite to loop in an expert on TCFD? I have two industry contacts that I can reach out to.

**Comment by PindyBhullar** [comment]
@ursvill @seanmcilroy29 - We can bring the resources in once we have something developed. It would be great to get their views.

**Comment by ursvill** [comment]
@PindyBhullar - updated

**Comment by seanmcilroy29** [comment]
Completed
