### ISSUE TITLE
TOSS Decision Trees workshop

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/toss#20]
# Context

Run an innovation workshop for the TOSS project to accelerate it's development and define key criteria such as the final deliverable.

# Actions

- [x] @PindyBhullar @sk16-dev @seanmcilroy29 populate the [Workshop Request form](https://docs.google.com/document/d/1X9xqS4iq1Nq-9FcJQ_u4BBuSiAdM57cHl7PxR-yy1is/edit#heading=h.r7xjaca2z7es) with their initial thoughts
- [x] Discuss the workshop in the 12 June project call
- [x] Announce workshop on the TOSS repository
- [x] @PindyBhullar @sk16-dev create workshop pre-read material
- [x] @PindyBhullar @sk16-dev define structure for Orientation workshop

**Comment by russelltrow** [comment]
Hey @PindyBhullar @sk16-dev I've just shared a workshop design document with you, please review and let me know your thoughts.

**Comment by russelltrow** [comment]
Hey @PindyBhullar @sk16-dev  I'm pleased to say we already have 9 confirmed participants and 2 more pending

**Comment by russelltrow** [comment]
@PindyBhullar @sk16-dev an email has just gone out to all the registered participants (12) providing further details on the workshop.

I've documented the workshop on the project wiki here: https://github.com/Green-Software-Foundation/toss/wiki/Decision-Tree-Workshops

I've also drafted a structure on Miro for the first 2 sessions, please take a look: https://miro.com/app/board/uXjVK6P7Dv0=/?share_link_id=91896744331

**Comment by ikolaxis** [comment]
Hi @russelltrow, please count me in for TOSS.

Thanks,
Ioannis Kolaxis, Accenture
